# Generated by Django 2.0.7 on 2018-07-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='blood_type',
            new_name='blood_type2',
        ),
    ]
