# Generated by Django 2.0.7 on 2018-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_auto_20180729_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='zodiac_sign',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
