# Generated by Django 2.0.7 on 2018-07-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_auto_20180729_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='blood_type2',
            new_name='blood_type',
        ),
    ]
