# Generated by Django 2.0.7 on 2018-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0004_auto_20180729_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.CharField(default='Undefined', max_length=200),
        ),
    ]
